# Generated by Django 6.0.4 on 2026-04-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('reference_no', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('doc_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_participation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'documents_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=20, null=True)),
                ('council_number', models.CharField(max_length=10, null=True)),
                ('session_time', models.CharField(max_length=10, null=True)),
                ('previous_session_date', models.DateField(blank=True, null=True)),
                ('invocation_by', models.CharField(max_length=50, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True, null=True)),
                ('agenda_finalized_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('participants', models.TextField()),
            ],
            options={
                'db_table': 'secretariat_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='STAFF', max_length=20)),
                ('office_or_district', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'accounts_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gazette.document')),
            ],
        ),
    ]
