# Generated by Django 6.0.4 on 2026-05-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccomment',
            name='replyTo',
            field=models.ForeignKey(blank=True, default=None, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='gazette.publiccomment'),
        ),
        migrations.AddField(
            model_name='publiccomment',
            name='tag',
            field=models.CharField(default='comment', max_length=10),
        ),
        migrations.AlterModelTable(
            name='publiccomment',
            table='gazette_publiccomment',
        ),
    ]
