# Generated by Django 6.0.4 on 2026-05-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0002_publiccomment_replyto_publiccomment_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccomment',
            name='replyTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gazette.publiccomment'),
        ),
    ]
