# Generated by Django 6.0.8 on 2026-09-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0003_alter_publiccomment_replyto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.TextField()),
                ('reference_no', models.CharField(max_length=100)),
                ('doc_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100, blank=True, default='')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_pdf_file', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'db_table': 'gazette_legacydocument',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='publiccomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_comments', to='gazette.document'),
        ),
    ]
