# Generated by Django 6.0.4 on 2026-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'committees_committee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Councilors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('district', models.IntegerField(choices=[(1, 'District 1'), (2, 'District 2')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='councilors/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if they are no longer in office')),
            ],
            options={
                'db_table': 'councilors_councilor',
                'managed': False,
            },
        ),
    ]
